//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by I:\projects\airsvn\trunk\AirDC.rc
//
#define IDD_ABOUTBOX                    100
#define IDC_FILETYPES                   101
#define IDC_COPY_SPEED                  102
#define IDC_TRAY_SHOW                   103
#define IDC_COPY_HUB                    104
#define IDC_REMOVE_OFFLINE              104
#define IDC_DISABLE_SOUNDS              105
#define IDC_CDMDEBUG_WINDOW             106
#define IDC_CONNECT_ALL                 106
#define IDD_GENERALPAGE                 107
#define IDC_DISCONNECT_ALL              107
#define IDC_COLLAPSE_ALL                108
#define IDC_EXPAND_ALL                  109
#define IDC_SEGMENTONE                  110
#define IDC_SEGMENTTWO                  111
#define IDC_SEGMENTTHREE                112
#define IDC_SEGMENTFOUR                 113
#define IDC_SEGMENTFIVE                 114
#define IDC_SEGMENTSIX                  115
#define IDC_SEGMENTSEVEN                116
#define IDC_DELETE                      116
#define IDC_SEGMENTEIGHT                117
#define IDC_SEGMENTNINE                 118
#define IDC_SEGMENTTEN                  119
#define IDC_COPY_HUBNAME                120
#define IDC_COPY_HUBADDRESS             121
#define IDC_MENU_SLOWDISCONNECT         122
#define IDR_MAINFRAME                   123
#define IDC_DEBUG_FILTER_TEXT           124
#define IDC_COLLAPSED                   125
#define IDC_USER_CMD_PREVIEW            126
#define IDC_CLEAR                       127
#define IDC_STOP                        127
#define IDC_COPY                        128
#define IDR_HUB                         129
#define IDC_PUB_LIST_DROPDOWN           130
#define IDC_SEARCH_PAUSE                130
#define IDC_HUBLIST                     131
#define IDC_EMOT                        131
#define IDC_OPEN_MY_LIST                132
#define IDC_SERVER                      133
#define IDC_EXTERNAL_IP                 133
#define IDC_USKIPLIST                   134
#define IDC_LOGMAINCHAT                 134
#define IDC_FILES                       135
#define IDC_LOGMAINCHAT2                135
#define IDC_SETTINGS_SCAN_OPTIONS       135
#define IDC_COPY_STATUS                 136
#define IDC_ITEMS                       137
#define IDC_WINAMP_BACK                 141
#define IDC_WINAMP_PLAY                 142
#define IDC_WINAMP_STOP                 143
#define IDC_WINAMP_PAUSE                144
#define IDC_WINAMP_NEXT                 145
#define IDC_WINAMP_VOL_UP               146
#define IDC_WINAMP_VOL_DOWN             147
#define IDC_WINAMP_VOL_HALF             148
#define IDC_WINAMP_SPAM                 149
#define IDC_REFRESH_MENU                150
#define IDC_MAX_MSG_LENGTH_SPIN         154
#define IDC_COPY_BEGIN                  162
#define IDC_COPY_END                    163
#define IDD_SHAREPAGE                   205
#define IDB_FOLDERS                     206
#define IDD_AIRAPPEARANCEPAGE           207
#define IDB_ARROWS                      208
#define IDD_LINE                        209
#define IDD_ADVANCEDPAGE                210
#define IDD_DOWNLOADPAGE                211
#define IDD_UPLOADPAGE                  212
#define IDD_SPEEDPAGE                   212
#define IDB_TOOLBAR                     213
#define IDD_APPEARANCEPAGE              213
#define IDR_FLATTAB                     214
#define IDR_PUBLICHUBS                  215
#define IDR_SEARCH                      216
#define IDR_FAVORITES                   217
#define IDR_PRIVATE                     218
#define IDR_DIRECTORY                   219
#define IDR_NOTEPAD                     220
#define IDB_TOOLBAR20                   221
#define IDR_QUEUE                       221
#define IDR_SPY                         222
#define IDD_FAVORITEHUB                 223
#define IDR_USERS                       224
#define IDD_LOGPAGE                     224
#define IDD_USER_COMMAND                230
#define IDR_FINISHED_DL                 231
#define IDR_FINISHED_UL                 232
#define IDR_ADLSEARCH                   233
#define IDD_ADLS_PROPERTIES             234
#define IDB_TOOLBAR20_HOT               235
#define IDD_UCPAGE                      236
#define IDR_NET_STATS                   237
#define IDR_RECENTS                     238
#define IDB_SPLASH                      240
#define IDD_HIGHLIGHTPAGE               240
#define IDR_UPLOAD_QUEUE                241
#define IDD_SOUNDS                      241
#define IDR_PRIVATE_OFF                 242
#define IDR_HUB_OFF                     243
#define IDB_O_SETTINGS_DLG              245
#define IDD_OPERACOLORS                 249
#define IDD_AVIPREVIEW                  250
#define IDD_PREVIEW                     252
#define IDB_STATE                       254
#define IDB_SEARCH_TYPES                257
#define IDD_FULTABSPAGE                 257
#define IDD_TOOLBARPAGE                 259
#define IDD_DOWNLOADDIR                 260
#define IDD_FAVORITE_DIRSPAGE           261
#define IDB_SPEEDS                      266
#define IDR_SYSTEM_LOG                  268
#define IDR_CDM                         270
#define IDD_UPDATE                      274
#define IDR_UPDATE                      276
#define IDB_FAVSTATES                   277
#define IDB_SHUTDOWN                    278
#define IDD_MAGNET                      281
#define IDI_MAGNET                      283
#define IDD_HASH_PROGRESS               284
#define IDD_POPUPS                      287
#define IDD_SDCPAGE                     288
#define IDD_USERLIST_COLOURS            289
#define IDD_HUB_LIST                    290
#define IDB_FLAGS                       291
#define IDD_WINDOWSPAGE                 292
#define IDD_EMOTICONS_DLG               293
#define IDB_EMOTICON                    295
#define IDD_NETWORKPAGE                 296
#define IDD_CERTIFICATESPAGE            297
#define IDD_QUEUEPAGE                   298
#define IDB_WINAMPBAR                   299
#define IDR_WINAMP_LOGO                 300
#define IDD_EXTRA                       301
#define IDD_AIRDCPAGE                   301
#define IDB_WINAMP_CONTROL              302
#define IDD_AUTOSEARCH                  302
#define IDD_AIRDOWNLOADSPAGE            303
#define IDD_AIRSHARINGPAGE              304
#define IDD_AUTOSEARCH_DLG              305
#define IDI_ICON8                       307
#define IDI_ICON9                       308
#define IDI_HO                          308
#define IDI_ICON10                      309
#define IDI_RUS                         310
#define IDB_BITMAP1                     312
#define IDB_USERS                       312
#define IDD_FULHIGHLIGHTPROPERTIES      313
#define IDD_HIGHLIGHTDIALOG             313
#define IDD_DIALOG1                     314
#define IDD_WIZARD                      314
#define IDD_DIRLIST_DLG                 316
#define IDI_GER                         318
#define IDI_ICON1                       324
#define IDI_FIN                         324
#define IDI_ICON2                       325
#define IDI_ICON3                       326
#define IDI_ICON4                       327
#define IDI_ICON5                       328
#define IDI_ICON6                       329
#define IDI_ICON7                       330
#define IDI_NOR                         331
#define IDI_RO                          332
#define IDI_POL                         333
#define IDI_FR                          334
#define IDR_EMOTICON                    335
#define IDD_PASS                        359
#define IDD_CHANGE_PASS                 360
#define IDR_WINAMP                      474
#define IDD_PARAM_DLG                   475
#define IDD_FAVHUBGROUPS                479
#define IDD_FORMVIEW                    500
#define IDC_REFRESH                     1000
#define IDC_NICK                        1001
#define IDC_EMAIL                       1002
#define IDC_DESCRIPTION                 1003
#define IDC_READD_ALL                   1004
#define IDC_CONNECTIONTYPE              1005
#define IDC_USERS                       1006
#define IDC_ACTIVE                      1006
#define IDC_CONNECTION                  1006
#define IDC_PASSIVE                     1007
#define IDC_CONNECTION3                 1007
#define IDC_DL_SPEED                    1007
#define IDC_PORT                        1008
#define IDC_DIRECTORIES                 1009
#define IDC_PORT_TCP                    1009
#define IDC_REMOVE_ALL                  1010
#define IDC_ADD                         1011
#define IDC_REMOVE                      1012
#define IDC_RECHECK                     1013
#define IDC_TOTAL                       1014
#define IDC_SLOTS                       1015
#define IDC_SLOTSPIN                    1016
#define IDC_TRANSFERS                   1017
#define IDC_DOWNLOADDIR                 1017
#define IDC_CONNECT                     1018
#define IDC_BROWSEDIR                   1018
#define IDC_RESULTS                     1019
#define IDC_LINE                        1019
#define IDC_EXTRA_SLOTS2                1019
#define IDC_DOWNLOADDIRTO               1020
#define IDC_EXTRASPIN                   1020
#define IDC_PRIVATEMESSAGE              1021
#define IDC_VERSION                     1021
#define IDC_GETLIST                     1022
#define IDC_ROLLBACK                    1022
#define IDC_NOTIFY                      1023
#define IDC_EDIT                        1026
#define IDC_NOTEPAD                     1027
#define IDC_AWAY                        1028
#define IDC_SEARCH_ALTERNATES           1029
#define IDC_SEARCH_ALTERNATES_DIR       1030
#define IDC_SELWINCOLOR                 1031
#define IDC_SELTEXT                     1032
#define IDC_SHAREHIDDEN                 1035
#define IDC_SHARE_SFV                   1036
#define IDC_QUEUE                       1037
#define IDC_SET_FONTS                   1038
#define IDC_HUBNICK                     1041
#define IDC_HUBPASS                     1042
#define IDC_NEWFAV                      1042
#define IDC_HUBNAME                     1043
#define IDC_SOURCE_TYPE                 1044
#define IDC_RAW_ONE                     1044
#define IDC_SIZE_TYPE                   1045
#define IDC_RAW_TWO                     1045
#define IDC_RAW_THREE                   1046
#define IDC_HUBDESCR                    1047
#define IDC_HUBADDR                     1048
#define IDC_RAW_FOUR                    1049
#define IDC_SETTINGS_LIST_CONFIG        1049
#define IDC_FORCE                       1050
#define IDC_RAW_FIVE                    1050
#define IDC_SETTINGS_BTN_TARGETDRIVE    1050
#define IDC_BUFFERSIZE                  1051
#define IDC_LANGUAGE                    1052
#define IDC_BROWSE                      1053
#define IDC_COPY_USER_ALL               1054
#define IDC_THANKS                      1055
#define IDC_DOWNLOADS                   1056
#define IDC_AIRTHANKS                   1056
#define IDC_SLOTSSPIN                   1057
#define IDC_MAXSPEED                    1058
#define IDC_SPEEDSPIN                   1059
#define IDC_FAVUSERS                    1060
#define IDC_PROXY                       1060
#define IDC_ADD_TO_FAVORITES            1061
#define IDC_FILESPIN                    1062
#define IDC_HELP_HOMEPAGE               1063
#define IDC_MCNDLSLOTS                  1063
#define IDC_MCNULSLOTS                  1064
#define IDC_LOG_DIRECTORY               1065
#define IDC_BROWSE_LOG                  1066
#define IDC_HELP_DISCUSS                1067
#define IDC_HELP_CUSTOMIZE              1069
#define IDC_SEARCH_SPY                  1070
#define IDC_LATEST                      1071
#define IDC_PRIVATE_MESSAGE_BEEP        1072
#define IDC_PRIVATE_MESSAGE_BEEP_OPEN   1073
#define IDC_MIN_UPLOAD_SPEED            1074
#define IDC_SETTINGS_TYPE               1074
#define IDC_MIN_UPLOAD_SPIN             1075
#define IDC_CHEVRON                     1076
#define IDC_OPEN_FILE_LIST              1077
#define IDC_TOTALS                      1077
#define IDC_SEARCH                      1078
#define IDC_RATIO                       1078
#define IDC_CLOSE_WINDOW                1080
#define IDC_FIND                        1081
#define IDC_NEXT                        1082
#define IDC_FINISHED                    1084
#define IDC_TEMP_DOWNLOAD_DIRECTORY     1084
#define IDC_CHANGE                      1084
#define IDC_BROWSETEMPDIR               1085
#define IDC_SOCKS_RESOLVE               1086
#define IDC_PROGRESS_BUMPED             1086
#define IDC_REMOVEALL                   1087
#define IDC_SOCKS_SERVER                1090
#define IDC_SOCKS_PORT                  1091
#define IDC_SOCKS_USER                  1092
#define IDC_SOCKS_PASSWORD              1093
#define IDC_FREESLOTS                   1094
#define IDC_TTHONLY                     1095
#define IDC_COPY_NICK                   1096
#define IDC_ADVANCED_BOOLEANS           1096
#define IDC_ADD_MENU                    1097
#define IDC_MOVE                        1098
#define IDC_REMOVE_MENU                 1098
#define IDC_MENU_ITEMS                  1099
#define IDC_CHANGE_MENU                 1100
#define IDC_UPDATE_HISTORY_TEXT         1100
#define IDC_NAME                        1101
#define IDC_COMMAND                     1102
#define IDC_PROGRESS_OVERRIDE           1102
#define IDC_HUB                         1103
#define IDC_PROGRESS_OVERRIDE2          1103
#define IDC_SHUTDOWNTIMEOUT             1104
#define IDC_PROGRESS_SEGMENT_SHOW       1104
#define IDC_COMMAND_DESCRIPTION         1105
#define IDC_SETTINGS_ODC_MENUBAR_RIGHT  1105
#define IDC_APPEARANCE_BOOLEANS         1106
#define IDC_SETTINGS_ODC_MENUBAR_LEFT   1106
#define IDC_DEFAULT_AWAY_MESSAGE        1107
#define IDC_INTERVAL                    1107
#define IDC_CLOSE_DISCONNECTED          1108
#define IDC_MATCH                       1108
#define IDC_OPEN_FOLDER                 1109
#define IDC_MAX_TAB_ROWS                1109
#define IDC_OPEN_FILE                   1110
#define IDC_SETTINGS_ODC_MENUBAR_BUMPED 1110
#define IDC_FILE_ADL_SEARCH             1111
#define IDC_SHUTDOWN                    1112
#define IDC_ADLLIST                     1113
#define IDC_MOVE_UP                     1114
#define IDC_MOVE_DOWN                   1115
#define IDC_HUBUSERDESCR                1116
#define IDC_FINISHED_UL                 1117
#define IDC_SEARCH_STRING               1118
#define IDC_SEARCH_HISTORY              1118
#define IDC_DEST_DIR                    1119
#define IDC_IS_ACTIVE                   1120
#define IDC_MIN_FILE_SIZE               1121
#define IDC_MAX_FILE_SIZE               1122
#define IDC_AUTOQUEUE                   1123
#define IDC_GO_TO_DIRECTORY             1124
#define IDC_IS_FORBIDDEN                1124
#define IDC_MATCH_QUEUE                 1125
#define IDC_IS_FORBIDDEN2               1125
#define IDC_VIEW_AS_TEXT                1129
#define IDC_PAGE                        1130
#define IDC_NET_STATS                   1131
#define IDC_SETTINGS_PERSONAL_INFORMATION 1132
#define IDC_SETTINGS_NICK               1133
#define IDC_SETTINGS_EMAIL              1134
#define IDC_SETTINGS_DESCRIPTION        1135
#define IDC_SETTINGS_ODC_SHUTDOWNTIMEOUT 1135
#define IDC_SETTINGS_IP                 1138
#define IDC_SETTINGS_PORT               1139
#define IDC_SETTINGS_SOCKS5_IP          1140
#define IDC_SETTINGS_SOCKS5_PORT        1141
#define IDC_SETTINGS_SOCKS5_USERNAME    1142
#define IDC_SETTINGS_SOCKS5_PASSWORD    1143
#define IDC_SETTINGS_UPLOAD_SPEED       1143
#define IDC_SETTINGS_UPLOAD_LINE_SPEED  1143
#define IDC_SETTINGS_DIRECTORIES        1144
#define IDC_SETTINGS_INCOMING           1144
#define IDC_SETTINGS_UPLOAD_SPEED2      1144
#define IDC_SETTINGS_DOWNLOAD_LINE_SPEED 1144
#define IDC_SETTINGS_DOWNLOAD_DIRECTORY 1145
#define IDC_SETTINGS_UNFINISHED_DOWNLOAD_DIRECTORY 1146
#define IDC_SETTINGS_PORT_TCP           1146
#define IDC_SETTINGS_DOWNLOAD_LIMITS    1147
#define IDC_SETTINGS_TARGETDRIVE_NOTE   1147
#define IDC_SETTINGS_DOWNLOADS_MAX      1148
#define IDC_SETTINGS_DOWNLOADS_SPEED_PAUSE 1149
#define IDC_SETTINGS_SPEEDS_NOT_ACCURATE 1150
#define IDC_SETTINGS_PUBLIC_HUB_LIST    1151
#define IDC_SETTINGS_PUBLIC_HUB_LIST_URL 1152
#define IDC_SETTINGS_PUBLIC_HUB_LIST_HTTP_PROXY 1153
#define IDC_SETTINGS_SHARED_DIRECTORIES 1154
#define IDC_SETTINGS_FILES_MAX          1154
#define IDC_SETTINGS_SHARE_SIZE         1155
#define IDC_SETTINGS_UPLOADS_MIN_SPEED  1156
#define IDC_SETTINGS_UPLOADS_SLOTS      1157
#define IDC_SETTINGS_APPEARANCE_OPTIONS 1159
#define IDC_SETTINGS_DEFAULT_AWAY_MSG   1160
#define IDC_SETTINGS_LANGUAGE_FILE      1161
#define IDC_SETTINGS_REQUIRES_RESTART   1162
#define IDC_SETTINGS_BACKGROUND_IMAGE   1162
#define IDC_SETTINGS_LOGGING            1163
#define IDC_SETTINGS_LOG_DIR            1164
#define IDC_SETTINGS_ROLLBACK           1167
#define IDC_SETTINGS_WRITE_BUFFER       1169
#define IDC_SETTINGS_MAX_TAB_ROWS       1170
#define IDC_SETTINGS_USER_MENU          1171
#define IDC_SETTINGS_KB                 1172
#define IDC_SETTINGS_B                  1173
#define IDC_SETTINGS_KBPS               1174
#define IDC_ADD_AS_FAVORITE             1175
#define IDC_SETTINGS_SEARCH_HISTORY     1178
#define IDC_HELP_DONATE                 1179
#define IDC_ADLSP_SEARCH                1184
#define IDC_ADLSP_TYPE                  1185
#define IDC_ADLSP_SIZE_MIN              1186
#define IDC_ADLSP_SIZE_MAX              1187
#define IDC_ADLSP_UNITS                 1188
#define IDC_ADLSP_DESTINATION           1189
#define IDC_AIRAPPEARANCE_BOOLEANS      1190
#define IDC_SETTINGS_AIRAPPEARANCE_OPTIONS 1191
#define IDC_SETTINGS_SEPARATOR          1194
#define IDC_SETTINGS_RAW                1195
#define IDC_SETTINGS_CHAT               1196
#define IDC_SETTINGS_PM                 1197
#define IDC_SETTINGS_HUB_MENU           1198
#define IDC_SETTINGS_SEARCH_MENU        1200
#define IDC_SETTINGS_CONTEXT            1201
#define IDC_SETTINGS_PARAMETERS         1202
#define IDC_SETTINGS_NAME               1203
#define IDC_SETTINGS_COMMAND            1204
#define IDC_SETTINGS_HUB                1205
#define IDC_SETTINGS_TO                 1206
#define IDC_RESULT                      1207
#define IDC_SETTINGS_FORMAT             1207
#define IDC_PREVIEW_BROWSE              1208
#define IDC_BTN_COLOR                   1208
#define IDC_COLOR_BUTTON                1209
#define IDC_MOVEUP                      1209
#define IDC_REFRESH_FILE_LIST           1210
#define IDC_PRESET                      1210
#define IDC_SCAN_MISSING                1212
#define IDC_SETTINGS_ONCE               1212
#define IDC_OPEN_DOWNLOADS              1213
#define IDC_SETTINGS_UPLOAD_BAR_COLOR   1214
#define IDC_PREVIEW_ARGUMENTS           1214
#define IDC_SETTINGS_DOWNLOAD_BAR_COLOR 1215
#define IDC_PREVIEW_EXTENSION           1215
#define IDC_AUTOSEGMENT                 1216
#define IDC_SETTINGS_SEGMENT_BAR_COLOR  1216
#define IDC_COPY_TTH                    1217
#define IDC_DONTBEGIN                   1217
#define IDC_SKIPLIST                    1217
#define IDC_SKIPLIST_DOWNLOAD           1218
#define IDC_EDIT1                       1218
#define IDC_CLIENT_NAME                 1218
#define IDC_CHUNKCOUNT                  1218
#define IDC_REFRESH_DELAY               1218
#define IDC_SKIPLIST_PRESET1            1218
#define IDC_MAX_DOWNLOAD_SP             1218
#define IDC_SKIP_SUBTRACT               1218
#define IDC_FILELIST_HL                 1218
#define IDC_SHARE_SAVE_TIME             1218
#define IDC_CLIENT_VERSION              1219
#define IDC_HIGH_PRIO_FILES             1219
#define IDC_MAX_UPLOAD_SP               1219
#define IDC_CLIENT_TAG                  1220
#define IDC_REFRESH_DELAY3              1220
#define IDC_DONT_SHARE_BIGGER_VALUE     1220
#define IDC_STATIC2                     1221
#define IDC_TOOLBAR_ACTUAL              1221
#define IDC_CLIENT_EXTENDED_TAG         1221
#define IDC_DU                          1221
#define IDC_POPUPTYPE                   1221
#define IDC_STATIC3                     1222
#define IDC_CLIENT_LOCK                 1222
#define IDC_CLIENT_PK                   1223
#define IDC_MAX_HASH_SPEED              1223
#define IDC_TOOLBAR_IMAGE               1224
#define IDC_CLIENT_SUPPORTS             1224
#define IDC_TREE1                       1224
#define IDC_STATICb                     1225
#define IDC_IMAGEBROWSE                 1225
#define IDC_CLIENT_TESTSUR_RESPONSE     1225
#define IDC_SETTINGS_MAX_HASH_SPEED     1225
#define IDC_SHOW_SPEED_CHECK            1225
#define IDC_TOOLBAR_POSSIBLE            1226
#define IDC_CLIENT_USER_CON_COM         1226
#define IDC_SETTINGS_MBS                1226
#define IDC_MOUSE_OVER                  1227
#define IDC_CLIENT_STATUS               1227
#define IDC_NORMAL                      1228
#define IDC_TOOLBAR_IMAGE_BOX           1229
#define IDC_VERSION_MISMATCH            1229
#define IDC_DOWNLOADDIR_DIR             1230
#define IDC_USE_EXTRA_VERSION           1230
#define IDC_TTH                         1230
#define IDC_DOWNLOADDIR_NAME            1231
#define IDC_DOWNLOADDIR_EXT             1232
#define IDC_MAGNET_QUEUE                1232
#define IDC_MAGNET_SEARCH               1233
#define IDC_CLIENT_FORMATTED_TAG        1233
#define IDC_MAGNET_REMEMBER             1234
#define IDC_MAGNET_HASH                 1235
#define IDC_CLIENT_CONNECTION           1236
#define IDC_MAGNET_NAME                 1236
#define IDC_MAGNET_NOTHING              1237
#define IDC_ADD_LINE                    1238
#define IDC_MAGNET_DISP_NAME            1238
#define IDC_MAGNET_DISP_HASH            1239
#define IDC_MAGNET_TEXT                 1240
#define IDC_SETTINGS_TIME_STAMPS_FORMAT 1241
#define IDC_TIME_STAMPS_FORMAT          1242
#define IDC_CLIENT_CHEATING_DESCRIPTION 1243
#define IDC_SETTINGS_ONLY_HASHED        1243
#define IDC_FH_HUB                      1243
#define IDC_COLOR_COMBO                 1243
#define IDC_FH_IDENT                    1244
#define IDC_FH_NAME                     1245
#define IDC_MAXCOMPRESS                 1246
#define IDC_HASH_PROGRESS               1246
#define IDC_FH_ADDRESS                  1246
#define IDC_MAX_COMPRESSION             1247
#define IDC_HASH_INDEXING               1247
#define IDC_FH_HUB_DESC                 1247
#define IDC_MAX_COMP_SPIN               1248
#define IDC_FILES_PER_HOUR              1248
#define IDC_FH_NICK                     1248
#define IDC_HASH_SPEED                  1249
#define IDC_FH_PASSWORD                 1249
#define IDC_FH_USER_DESC                1250
#define IDC_TIME_LEFT                   1251
#define IDC_MOVEDOWN                    1251
#define IDC_SETTINGS_FAVORITE_DIRECTORIES 1252
#define IDC_SHUTDOWN_SPIN               1253
#define IDC_STATISTICS                  1253
#define IDC_FAVORITE_DIRECTORIES        1253
#define IDC_KB                          1254
#define IDC_TAB_SIZE                    1254
#define IDC_SEG_NUMBER                  1255
#define IDC_CURRENT_FILE                1255
#define IDC_SEG_NUMBER_SPIN             1256
#define IDC_INTERVAL_SPIN               1256
#define IDC_LIST_ADD                    1256
#define BAA                             1257
#define IDC_SEARCH_EDIT                 1257
#define IDC_MATCH_SPIN                  1257
#define IDC_LIST_EDIT_BOX               1257
#define CAA                             1258
#define IDC_SEARCH_SPIN                 1258
#define IDC_LIST_UP                     1258
#define IDC_BEGIN_EDIT                  1259
#define IDC_LIST_DOWN                   1259
#define IDC_BEGIN_SPIN                  1260
#define IDC_LIST_REMOVE                 1260
#define IDC_LIST_DESC                   1261
#define AAA                             1262
#define IDC_LIST_LIST                   1262
#define IDC_SOUNDLIST                   1263
#define IDC_RENAME                      1263
#define IDC_SB_SKIPLIST_DOWNLOAD        1263
#define IDC_ST_SKIPLIST_DOWNLOAD        1264
#define IDC_UPDATE_URL                  1264
#define IDC_REGEXP_TESTER_TEXT          1264
#define IDC_LIST_EDIT                   1264
#define IDC_ST_HIGH_PRIO_FILES          1265
#define IDC_CHANGE_COLOR                1266
#define IDC_PORT_UDP                    1266
#define IDC_USERLIST_IMAGE              1267
#define IDC_SETTINGS_PORT_UDP           1267
#define IDC_USERLIST                    1268
#define IDC_IMPORT                      1269
#define IDC_EXPORT                      1270
#define IDC_BACK_IMAGE                  1270
#define IDC_SETTINGS_GET_USER_COUNTRY   1271
#define IDC_SB_HIGH_PRIO_FILES          1272
#define IDC_UP_COMBO                    1273
#define IDC_LOG_FORMAT                  1273
#define IDC_SB_TAB_COLORS               1273
#define IDC_DOWN_COMBO                  1274
#define IDC_LOG_FILE                    1274
#define IDC_SB_TAB_SIZE                 1274
#define IDC_SLASH                       1275
#define IDC_LOG_OPTIONS                 1275
#define IDC_SETTINGS_FILE_NAME          1276
#define IDC_ALTERNATE_COLOR             1277
#define IDC_SETTINGS_FILELIST_MENU      1278
#define IDC_PURGE                       1279
#define IDC_KBPS                        1280
#define IDC_MINUTES                     1281
#define IDC_SEARCH_HISTORY_SPIN         1281
#define IDC_PLAY                        1282
#define IDC_POPUPLIST                   1283
#define IDC_COMBO1                      1284
#define IDC_SB_HIGHLIGHT                1285
#define IDC_EDIT2                       1285
#define IDC_AIRDC_SLOT                  1285
#define IDC_SKIPLIST_PRESET2            1285
#define IDC_EXPLAIN                     1285
#define IDC_EDIT3                       1286
#define IDC_BIND_ADDRESS                1286
#define IDC_SKIPLIST_PRESET3            1286
#define IDC_STATIC1                     1287
#define IDC_SETTINGS_BIND_ADDRESS_HELP  1287
#define IDC_REGEXP_TESTER_BUTTON        1288
#define IDC_BIND_ADDRESS2               1288
#define IDC_S                           1290
#define IDC_FLAT                        1291
#define IDC_S2                          1291
#define IDC_TAB_DIRTY_BLEND             1292
#define IDC_FLAT_SPIN                   1292
#define IDC_DEFAULT                     1293
#define IDC_SB_TAB_DIRTY_BLEND          1293
#define IDC_CONN_BORDER                 1294
#define IDC_CH_STATUS_HUB_BOLD          1294
#define IDC_FH_CONN                     1294
#define IDC_CLIENT_PROFILE_RAW          1295
#define IDC_MULTISOURCE                 1295
#define IDC_SETTINGS_OUTGOING           1295
#define IDC_CH_STATUS_HUB_BOLD2         1295
#define IDC_BOLD_HUB_TABS_ON_KICK       1295
#define IDC_REGEXP_TESTER_COMBO         1296
#define IDC_MULTISOURCE_COMBO           1296
#define IDC_CH_ICONS                    1296
#define IDC_PUB_LIST_CONFIG             1297
#define IDC_ODC_STYLE                   1297
#define IDC_OVERRIDE                    1297
#define IDC_CH_BLEND                    1297
#define IDC_WINDOWS_STARTUP             1298
#define IDC_SETTINGS_PORTS              1298
#define IDC_SETTINGS_AUTO_OPEN          1299
#define IDC_SETTINGS_BIND_ADDRESS       1299
#define IDC_SETTINGS_WINDOWS_OPTIONS    1300
#define IDC_ADLSEARCH_ACTION            1300
#define IDC_PRIO_HIGHEST_SIZE           1300
#define IDC_WINDOWS_OPTIONS             1301
#define IDC_ADLSEARCH_RAW_ACTION        1301
#define IDC_PRIO_HIGH_SIZE              1301
#define IDC_REFRESH_SPIN                1301
#define IDC_DIRECT                      1302
#define IDC_PRIO_NORMAL_SIZE            1302
#define IDC_ROLLBACK_SPIN               1302
#define IDC_INCOMING_SPIN               1302
#define IDC_FIREWALL_UPNP               1303
#define IDC_PRIO_LOW_SIZE               1303
#define IDC_SHUTDOWNACTION              1303
#define IDC_FIREWALL_NAT                1304
#define IDC_SETTINGS_PRIO_HIGHEST       1304
#define IDC_READ_SPIN                   1304
#define IDC_POPUPGROUP                  1304
#define IDC_PARAM_NAME                  1304
#define IDC_FIREWALL_PASSIVE            1305
#define IDC_SETTINGS_PRIO_HIGH          1305
#define IDC_AUTO_SEARCH_LIMIT_SPIN      1305
#define IDC_PARAM_REGEXP                1305
#define IDC_DIRECT_OUT                  1306
#define IDC_SETTINGS_PRIO_NORMAL        1306
#define IDC_TAB_SPIN                    1306
#define IDC_STTIC                       1306
#define IDC_SOCKS5                      1307
#define IDC_SETTINGS_PRIO_LOW           1307
#define IDC_WRITE_SPIN                  1307
#define IDC_SETTINGS_KB3                1308
#define IDC_HASH_SPIN                   1308
#define IDC_GETIP                       1308
#define IDC_SETTINGS_KB4                1309
#define IDC_BUFFER_SPIN                 1309
#define IDC_CHECK1                      1309
#define IDC_USE_HIGHLIGHT               1309
#define IDC_DOWNLOAD_SKIPLIST_USE_REGEXP 1309
#define IDC_FAV_SEARCH_INTERVAL         1309
#define IDC_PASSWD_PROTECT_TRAY_CHCKBOX 1309
#define IDC_REFRESH_ON_SHAREPAGE        1309
#define IDC_SETTINGS_KB5                1310
#define IDC_DOWNCONN_SPIN               1310
#define IDC_HIGHEST_PRIORITY_USE_REGEXP 1310
#define IDC_FAV_SEARCH_INTERVAL_BOX     1310
#define IDC_SETTINGS_KB6                1311
#define IDC_ST_REFRESH_DELAY            1311
#define IDC_FAV_SEARCH_INTERVAL_SPIN    1311
#define IDC_SETTINGS_AUTOPRIO           1312
#define IDC_OTHER_BORDER                1312
#define IDC_SETTINGS_SEGMENT            1313
#define IDC_BOLD_BOOLEANS               1313
#define IDC_BUTTON1                     1313
#define IDC_BLACK                       1313
#define IDC_SLOTS_GROUP                 1313
#define IDC_SETTINGS_BOLD_CONTENTS      1314
#define IDC_SHARE_SKIPLIST_USE_REGEXP   1314
#define IDC_UPDATE_CLIENTS              1314
#define IDC_SETTINGS_MCNSLOTS           1314
#define IDC_PRIO_HIGH_SIZE2             1314
#define IDC_SETTINGS_CONFIRM_OPTIONS    1315
#define IDC_FAV_DL                      1315
#define IDC_LINE_SPEED                  1315
#define IDC_SETTINGS_KB7                1315
#define IDC_CONFIRM_OPTIONS             1316
#define IDC_RADIO1                      1316
#define IDC_PRIVATE                     1316
#define IDC_PUBLIC                      1316
#define IDC_SLOTS_GROUP2                1316
#define IDC_PRIO_LOW_SIZE2              1316
#define IDC_SOCKET_IN_BUFFER            1317
#define IDC_UPDATE_LANGUAGE             1317
#define IDC_GROUP                       1317
#define IDC_FAVGROUP                    1317
#define IDC_SETTINGS_KB8                1317
#define IDC_SOCKET_OUT_BUFFER           1318
#define IDC_TLS_CERTIFICATE_FILE        1318
#define IDC_PORT_TLS                    1318
#define IDC_FH_RAW                      1318
#define IDC_SETTINGS_SOCKET_OUT_BUFFER  1319
#define IDC_PLAYER_PATH                 1319
#define IDC_ORDER_BALANCED              1319
#define IDC_SETTINGS_SOCKET_IN_BUFFER   1320
#define IDC_PREVIEW_NAME_TEXT           1320
#define IDC_ICON_SIZE                   1321
#define IDC_PREVIEW_APPLICATION_TEXT    1321
#define IDC_ICON_SIZE_HOVER             1322
#define IDC_PREVIEW_ARGUMENTS_TEXT      1322
#define IDC_PREVIEW_EXTENSION_TEXT      1323
#define IDC_GROUP_PROPERTIES            1323
#define IDC_BW_SIMPLE                   1324
#define IDC_NAME_STATIC                 1324
#define IDC_BW_BOTH                     1325
#define IDC_BACKUP                      1325
#define IDC_SETTINGS_NOMINALBW          1326
#define IDC_HELP_GUIDES                 1327
#define IDC_ST_AIRDC_SLOT               1327
#define IDC_DUPE_SEARCH                 1328
#define IDC_NOTE                        1329
#define IDC_DUPE_CHAT                   1329
#define IDC_SETTING_ALLOW_CONNECTION_TO_PASSED_HUBS 1330
#define IDC_DUPE_CHAT2                  1330
#define IDC_DUPE_FILELISTS              1330
#define IDC_CHECK2                      1331
#define IDC_REFRESH_VNAME_ON_SHAREPAGE  1331
#define IDC_SHOW_JOIN                   1331
#define IDC_RELEASE_LINKS               1331
#define IDC_DECREASE_RAM                1331
#define IDC_ASEARCH                     1332
#define IDC_REFRESH_VNAME_ON_SHAREPAGE2 1332
#define IDC_SEARH_SKIPLIST_PRESET       1333
#define IDC_PRE1                        1334
#define IDC_PRE2                        1335
#define IDC_SEP                         1336
#define IDC_PRE3                        1336
#define IDC_WINAMP_PATH                 1337
#define IDC_IPUPDATE                    1338
#define IDC_OPEN_SYSTEMLOG              1339
#define IDC_UPDATE_PROGRESS             1340
#define IDC_CZDC_WINAMP                 1341
#define IDC_WINAMP                      1342
#define IDC_SETTINGS_INCOMING_REFRESH_TIME 1342
#define IDC_WINAMP_HELP                 1343
#define IDC_STATIC_M                    1343
#define IDC_POPUP_TIME                  1344
#define IDC_SYS_LOG                     1344
#define IDC_POPUP_TIME_STR              1345
#define IDC_SYSTEM_LIST                 1345
#define IDNEXT                          1347
#define IDC_LIST1                       1348
#define IDC_CONNECTION2                 1349
#define IDC_RAR                         1350
#define IDC_PRIVATE_HUB                 1351
#define IDC_DOWNLOAD_TEXT               1353
#define IDC_DOWN_SPEED                  1354
#define IDC_WINAMP_BROWSE               1356
#define IDC_DOWN_SPEED_SPIN             1356
#define IDC_UP_SPEED_SPIN               1357
#define IDC_SETTINGS_NOMINALBW2         1358
#define IDC_HIDE_SHARE                  1359
#define IDC_DOWNLOAD_SLOTS              1359
#define IDC_LANG_SWE                    1360
#define IDC_DOWNLOAD_S_SPIN             1360
#define IDC_ENG                         1361
#define IDC_UPLOAD_SLOTS                1361
#define IDC_LANG_FIN                    1362
#define IDC_UPLOAD_S_SPIN               1362
#define IDC_LANG_RO                     1363
#define IDC_MAX_AUTO_OPENED             1363
#define IDC_LANG_HUN                    1364
#define IDC_POPUP_TYPE                  1364
#define IDC_FILE_SLOTS                  1364
#define IDC_LANG_DAN                    1365
#define IDC_SPIN4                       1365
#define IDC_FILE_S_SPIN                 1365
#define IDC_LANG_ITA                    1366
#define IDC_CHECK3                      1366
#define IDC_HIGHLIGHT                   1366
#define IDC_CHAT_NOTIFY                 1366
#define IDC_LANG_NOR                    1367
#define IDC_SPIN1                       1367
#define IDC_LOG_LINES_SPIN              1367
#define IDC_SAVE_SPIN                   1367
#define IDC_UPDATE_BL                   1368
#define IDC_TEST                        1368
#define IDC_POPUP_TITLE_FONT            1368
#define IDC_LANG_POL                    1368
#define IDC_LOG_LINESTEXT               1368
#define IDC_LANG_POR                    1369
#define IDC_COMBOBOXEX1                 1369
#define IDC_NATT                        1370
#define IDC_SORT_DIRS                   1370
#define IDC_CONNECTION_DETECTION        1371
#define IDC_DONT_SHARE_BIGGER_THAN      1371
#define IDC_POPUP_FONT                  1372
#define IDC_CURRENT_LIST_BROWSE         1372
#define IDC_VIEW_BL                     1372
#define IDC_SETTINGS_MB2                1372
#define IDC_LANG_FR                     1373
#define IDC_SETTINGS_KIB                1373
#define IDC_LANG_D                      1374
#define IDC_BUTTON2                     1374
#define IDC_ICONS_RESTORE               1374
#define IDC_PLAYER_COMBO                1375
#define IDC_LANG_RUS                    1375
#define IDC_MCN_SPIN                    1375
#define IDC_REMOVE_FILE                 1376
#define IDC_MCN_SPIN2                   1376
#define IDC_LANG_GER                    1377
#define IDC_SETTINGS_MAX_MCN            1377
#define IDC_SETTINGS_MAX_MCN_UL         1378
#define IDC_MCN_AUTODETECT              1379
#define IDC_SETTINGS_MAX_MCN_DL         1380
#define IDC_DL_AUTODETECT               1381
#define IDC_UL_AUTODETECT               1382
#define IDC_UL_AUTODETECT_WIZ           1383
#define IDC_DL_AUTODETECT_WIZ           1384
#define IDC_SETTINGS_PROFILE            1385
#define IDC_WIZARD_SKIPLIST             1385
#define IDC_SPEEDTEST                   1386
#define IDC_MAX_DL_WIZ                  1388
#define IDC_MAX_DL_SPEED_WIZ            1389
#define IDC_UPLOAD_SLOTS_WIZ            1390
#define IDC_MAX_MSG_LENGTH              1391
#define IDC_OPEN_EXTRA_WIZ              1391
#define IDC_MAX_MSG_LENGTH_STR          1392
#define IDC_MAX_AUTO_WIZ                1392
#define IDC_POPUP_COLORS                1393
#define IDC_WIZARD_NOTETOP              1393
#define IDC_POPUP_BACKCOLOR             1394
#define IDC_WIZARD_NOTESPEED            1394
#define IDC_POPUPFILE                   1395
#define IDC_SKIP_SUBTRACT_TEXT          1395
#define IDC_POPUP_IMAGE_GP              1396
#define IDC_UNDERLINE_LINKS             1396
#define IDC_POPUPBROWSE                 1397
#define IDC_UNDERLINE_DUPES             1397
#define IDC_LIST_HL_TEXT                1397
#define IDC_LIST_HL_EXAMPLE             1398
#define IDC_POPUP_TIME_SPIN             1399
#define IDC_DOWNLOAD_OPTIONS            1399
#define IDC_OTHER_QUEUE_OPTIONS         1400
#define IDC_ORDER_PROGRESS              1400
#define IDC_COPY_EXACT_SIZE             1401
#define IDC_ORDER_ADDED                 1401
#define IDC_DUPE_TEXT                   1402
#define IDC_ORDER_RANDOM                1402
#define IDC_GROUPS                      1403
#define IDC_PRIO_RANDOM2                1403
#define IDC_DOWNLOAD_ORDER              1404
#define IDC_SHARE_SAVE                  1405
#define IDC_FILELIST_DIFF               1406
#define IDC_SETTINGS_MEBIBYES           1406
#define IDC_SETTINGS_MEBIBITS           1406
#define IDC_THEME_TEXT                  1406
#define IDC_SETTINGS_MEBIBITS2          1407
#define IDC_STYLES                      1408
#define IDC_AVAILABLE_STYLES            1409
#define IDC_MATCH_ADL                   1410
#define IDC_SYSTEM_LOG                  1412
#define IDC_OPEN_SYSTEM_LOG             1413
#define IDC_TLS_PRIVATE_KEY_FILE        1414
#define IDC_TLS_TRUSTED_CERTIFICATES_PATH 1415
#define IDC_AUTO_REFRESH_TIME           1419
#define IDC_SETTINGS_AUTO_REFRESH_TIME  1420
#define IDC_AUTO_SEARCH_LIMIT           1421
#define IDC_TLS_OPTIONS                 1421
#define IDC_SETTINGS_AUTO_SEARCH_LIMIT  1422
#define IDC_GENERATE_CERTS              1422
#define IDC_CLOSE_ALL_PM                1423
#define IDC_BROWSE_PRIVATE_KEY          1423
#define IDC_SETTINGS_AUTO_SEARCH_LIMIT2 1423
#define IDC_SETTINGS_DOWNCONN           1423
#define IDC_CLOSE_ALL_OFFLINE_PM        1424
#define IDC_BROWSE_CERTIFICATE          1424
#define IDC_DOWNCONN                    1424
#define IDC_CLOSE_ALL_DIR_LIST          1425
#define IDC_BROWSE_TRUSTED_PATH         1425
#define IDC_CLOSE_ALL_SEARCH_FRAME      1426
#define IDC_SETTINGS_PORT_TLS           1427
#define IDC_MATCH_ALL                   1428
#define IDC_ENCODINGTEXT                1429
#define IDC_ENCODING                    1430
#define IDC_UPDATE_VERSION              1445
#define IDC_UPDATE_VERSION_CURRENT_LBL  1446
#define IDC_UPDATE_VERSION_LATEST_LBL   1447
#define IDC_UPDATE_VERSION_CURRENT      1448
#define IDC_UPDATE_VERSION_LATEST       1449
#define IDC_UPDATE_HISTORY              1450
#define IDC_HISTORY_STATUS              1451
#define IDC_LOADING                     1451
#define IDC_COUNT                       1452
#define IDC_UPDATE_DOWNLOAD             1452
#define IDC_UPDATE                      1453
#define IDC_LIST_VIEWER_GB              1453
#define IDC_FAV_DLG_GROUP               1454
#define IDC_FAVGROUP_BOX                1454
#define IDC_LIST_OPTIONS                1455
#define IDC_UPDATE_VERSION_LANGUAGE_LBL 1455
#define IDC_UPDATE_LOCATION             1456
#define IDC_CURRENT_LIST_STR            1457
#define IDC_UPDATE_LOCATION_STR         1458
#define IDC_UPDATE_LANGUAGE_CURRENT     1458
#define IDC_CURRENT_LIST                1459
#define IDC_LIST_NAME                   1460
#define IDC_UPDATE_LANGUAGE_LATEST      1460
#define IDC_SEARCH_IP                   1461
#define IDC_MATCH_OPTIONS               1462
#define IDC_ACTIONS                     1463
#define IDC_TEXT_TO_MATCH               1464
#define IDC_ST_MATCH_TYPE               1465
#define IDC_BOLD                        1466
#define IDC_ITALIC                      1467
#define IDC_UNDERLINE                   1468
#define IDC_STRIKEOUT                   1469
#define IDC_POPUP                       1470
#define IDC_INCLUDENICK                 1471
#define IDC_WHOLELINE                   1472
#define IDC_CASESENSITIVE               1473
#define IDC_WHOLEWORD                   1474
#define IDC_TABCOLOR                    1475
#define IDC_LASTLOG                     1476
#define IDC_MATCHTYPE                   1477
#define IDC_STRING                      1478
#define IDC_BGCOLOR                     1479
#define IDC_FGCOLOR                     1480
#define IDC_SELECT_SOUND                1481
#define IDC_SOUND                       1482
#define IDC_HAS_BG_COLOR                1483
#define IDC_HAS_FG_COLOR                1484
#define IDC_PRESETMENU                  1485
#define IDC_PASTE                       1486
#define IDC_RESIZE_LINES                1507
#define IDC_RESIZE_LINES_SPIN           1508
#define IDC_MAX_RESIZE_LINES_STR        1509
#define IDC_USERLIST_COLORS             1517
#define IDC_METACRITIC                  1521
#define IDC_TABCOLOR_LIST               1522
#define IDC_SELECT_TAB_COLOR            1523
#define IDC_SAMPLE_TAB_COLOR            1524
#define IDC_RESET_TAB_COLOR             1525
#define IDC_SEARCH_BY_TTH               1526
#define IDC_THEMES                      1526
#define IDC_GOOGLE                      1527
#define IDC_IMDB                        1528
#define IDC_GOOGLE_FULL                 1530
#define IDC_TVCOM                       1531
#define IDC_GOOGLE_TITLE                1532
#define IDC_REMOVE_ON_HIT               1533
#define IDC_DL_TO                       1534
#define IDC_TARGET_PATH                 1535
#define IDC_AUTOPRIORITY                1572
#define IDC_SETTINGS_ODC_MENUBAR        1612
#define IDC_SETTINGS_ODC_MENUBAR_USETWO 1613
#define IDC_SETTINGS_ODC_MENUBAR_COLOR  1614
#define IDC_SETTINGS_ODC_MENUBAR2       1615
#define IDC_PROGRESS_COLOR_DOWN_SHOW    1616
#define IDC_PROGRESS_COLOR_UP_SHOW      1617
#define IDC_PREVIEW_APP                 1700
#define IDC_HASH_PROGRESS_AUTO_CLOSE    1701
#define IDC_TOOLBAR_ADD                 2200
#define IDC_HOTBROWSE                   2201
#define IDC_TOOLBAR_REMOVE              2202
#define IDC_PREVIEW_NAME                2223
#define IDC_PREVIEW_APPLICATION         2224
#define IDC_TOOLBAR_HOT_IMAGE           2224
#define IDC_LIMITER                     2225
#define IDC_STEALTH                     2226
#define IDC_HELP_GEOIPFILE              2227
#define IDC_EMOMENU                     2228
#define IDC_MENU_SEARCH                 2229
#define IDC_MENU_SEARCH_TTH             2230
#define IDC_PAUSE                       2231
#define IDC_PAUSED                      2232
#define IDC_RESUMED                     2233
#define IDC_SETTINGS_AUTO_SLOTS         3023
#define IDC_AUTO_SLOTS                  3024
#define IDC_AUTO_SLOTS_SPIN             3025
#define IDC_SETTINGS_PARTIAL_SLOTS      3026
#define IDC_PARTIAL_SLOTS               3027
#define IDC_PARTIAL_SLOTS_SPIN          3028
#define IDC_SEARCHLEFT                  3029
#define IDC_SEARCHDIR                   3030
#define IDC_DOWNLOAD_TARGET             5000
#define IDC_DOWNLOAD_TARGET_DIR         5500
#define IDC_SELECT_WINDOW               6000
#define IDC_USER_COMMAND                6500
#define IDC_PRIORITY_PAUSED             7000
#define IDC_PRIORITY_LOWEST             7001
#define IDC_PRIORITY_LOW                7002
#define IDC_PRIORITY_NORMAL             7003
#define IDC_PRIORITY_HIGH               7004
#define IDC_PRIORITY_HIGHEST            7005
#define IDC_DOWNLOAD_WHOLE_TARGET       7500
#define IDC_DOWNLOAD_FAVORITE_DIRS      8500
#define IDC_PASSWD_PROTECT_STATIC       8600
#define IDC_PASSWD_PROTECT_CHCKBOX      8671
#define IDC_PASSWD_BUTTON               8672
#define IDC_PSWD_CHNG_STATIC            8673
#define IDC_PSWD_CHNG_OLD               8674
#define IDC_PSWD_CHNG_NEW               8675
#define IDC_PSWD_CHNG_CONFIRM_NEW       8676
#define IDC_LINE2                       8677
#define IDC_LINE3                       8678
#define IDC_DOWNLOAD_WHOLE_FAVORITE_DIRS 9000
#define IDR_TRAY_PM                     10000
#define IDR_TRAY_HUB                    10001
#define IDC_EXTRASLOTSSPIN              10002
#define IDC_EXTRA_DOWN_SLOT             10003
#define IDC_EXTRA_DOWNLOADS_MAX         10004
#define IDC_ERROR_COLOR                 10005
#define IDC_UPTIME                      10007
#define IDC_BACK_COLOR                  10011
#define IDC_TEXT_STYLE                  10014
#define IDC_TEXT_COLOR                  10015
#define IDC_PREVIEW                     10017
#define IDC_TEXT_STYLES                 10019
#define IDC_EXTRA_SLOTS                 10020
#define IDC_EXTRA_SLOTS_SPIN            10021
#define IDC_SMALL_FILE_SIZE             10022
#define IDC_SMALL_FILE_SIZE_SPIN        10023
#define IDC_BLACK_AND_WHITE             10024
#define IDC_DEFAULT_STYLES              10025
#define IDC_COPY_TAG                    10026
#define IDC_COPY_FILENAME               10027
#define IDC_COPY_PATH                   10028
#define IDC_COPY_SIZE                   10030
#define ID_VIEW_TRANSFER_VIEW           10031
#define IDC_OPEN_HUB_LOG                10032
#define IDC_OPEN_USER_LOG               10033
#define IDC_COPY_TIME                   10034
#define IDC_COPY_TYPE                   10035
#define IDC_MANAGE_GROUPS               10037
#define IDC_NONE                        10041
#define IDD_TEXT_STYLES                 10042
#define IDC_HISTORY                     10043
#define IDD_KICK                        10044
#define IDC_PUBLIC_MESSAGE              10050
#define IDC_SELECT_USER                 10051
#define IDC_COPY_ACTUAL_LINE            10052
#define IDC_COPY_DESCRIPTION            10053
#define IDC_COPY_EMAIL_ADDRESS          10054
#define IDC_AUTOSCROLL_CHAT             10055
#define IDC_WHOIS_IP                    10056
#define IDC_BAN_IP                      10057
#define IDC_UNBAN_IP                    10058
#define IDC_CLIENT                      10059
#define IDC_COPY_URL                    10060
#define IDC_BOLD_AUTHOR_MESS            10061
#define IDC_USER_HISTORY                10062
#define IDC_IGNORE                      10063
#define IDC_UNIGNORE                    10064
#define IDC_GRANTSLOT                   10080
#define IDC_GRANTSLOT_HOUR              10081
#define IDC_GRANTSLOT_DAY               10082
#define IDC_GRANTSLOT_WEEK              10083
#define IDC_UNGRANTSLOT                 10084
#define IDC_UPLOAD_QUEUE                10085
#define IDC_PROGRESS_TEXT_COLOR_DOWN    10102
#define IDC_PROGRESS_TEXT_COLOR_UP      10103
#define IDC_CZDC_PM_SOUND               10107
#define IDC_CZDC_SECONDARY_TRANSFER     10112
#define IDC_CZDC_PROGRESS_COLOR         10115
#define IDC_CZDC_PROGRESS_TEXT          10117
#define IDC_INTERVAL_TEXT               10118
#define IDC_MATCH_QUEUE_TEXT            10119
#define IDC_SETCZDC_PM_LINES            10121
#define IDC_CZDC_PREVIEW                10123
#define IDC_CZDC_SMALL_SLOTS            10130
#define IDC_CZDC_SMALL_SIZE             10131
#define IDC_CZDC_NOTE_SMALL             10132
#define IDC_SETTINGS_MCN_NOTE           10133
#define IDC_USER_CMD_DESCRIPTION        10140
#define IDC_USER_CMD_EXAMPLE            10141
#define IDC_COPY_EXACT_SHARE            10145
#define IDC_COPY_IP                     10146
#define IDC_COPY_NICK_IP                10147
#define IDC_PM_LINES                    10147
#define IDC_COPY_ALL                    10148
#define IDC_PM_LINESSPIN                10148
#define IDC_LOG_LINES                   10149
#define ID_GET_TTH                      10151
#define IDC_COPY_LINK                   10152
#define ID_WIZARD                       10153
#define IDC_COPY_DIR                    10154
#define IDC_COPY_DIRECTORY              10155
#define IDC_SFV_CHECH_FOLDER            10161
#define IDC_REBUILD_TOOLBAR             10162
#define IDC_MAGNET_SIZE                 10164
#define IDC_MAGNET_DISP_SIZE            10165
#define IDC_TIMESTAMP_HELP              10167
#define IDC_CHECKSFV                    10168
#define IDC_SFV_CHECH_FILE              10169
#define IDC_USERLIST_DBLCLICK           10190
#define IDC_TRANSFERLIST_DBLCLICK       10191
#define IDC_USERLISTDBLCLICKACTION      10192
#define IDC_TRANSFERLISTDBLCLICKACTION  10193
#define IDC_CHATDBLCLICKACTION          10194
#define IDC_CHAT_DBLCLICK               10195
#define IDC_HEADER_MENU                 10196
#define IDC_FINDMISSING                 10197
#define IDC_REFRESH_WINAMP              11011
#define IDC_WINAMP_LIST                 11012
#define IDC_POSITION                    11013
#define ID_SHELLCONTEXTMENU_MIN         12000
#define ID_SHELLCONTEXTMENU_MAX         14000
#define IDC_REGEXP                      15000
#define IDC_BACKGROUND_IMAGE            15001
#define IDC_RECONNECT_DISCONNECTED      15002
#define IDC_FAV_NO_PM                   15003
#define IDD_IGNOREPAGE                  15005
#define IDC_IGNORE_ADD                  15006
#define IDD_PRIOPAGE                    15006
#define IDD_PRIORITYPAGE                15006
#define IDC_IGNORE_REMOVE               15007
#define IDC_IGNORE_CLEAR                15008
#define IDC_IGNORELIST                  15009
#define IDC_IGNORE_USE_REGEXP_OR_WC     15010
#define IDC_IGNORELIST_EDIT             15011
#define IDC_MISC_IGNORE                 15012
#define IDC_FAV_DL_SPEED                15013
#define IDC_OPEN_FIRST_X_HUB            15014
#define IDC_OPEN_FIRST                  15015
#define IDC_ANTIVIR_PATH                15016
#define IDC_ANTIVIR_BROWSE              15017
#define IDC_AIRDC_ANTI_VIR              15018
#define IDC_SKIPLIST_SHARE              15019
#define IDC_FREE_SLOTS_EXTENSIONS       15020
#define IDC_MINISLOTS_EXTENSIONS        15021
#define IDC_INCOMING_REFRESH_TIME       15022
#define IDC_SHARE_REFRESH_TIME          15023
#define IDC_SB_SKIPLIST_SHARE           15024
#define IDC_STATIC4                     15024
#define IDC_ST_SKIPLIST_SHARE_EXT       15025
#define IDC_STATIC5                     15025
#define IDC_SB_MINISLOTS                15026
#define IDC_ST_MINISLOTS_EXT            15027
#define IDC_DISCONNECTING_ENABLE        15028
#define IDC_CZDC_SLOW_DISCONNECT        15029
#define IDC_CZDC_I_DOWN_SPEED           15030
#define IDC_CZDC_TIME_DOWN              15031
#define IDC_I_DOWN_SPEED                15032
#define IDC_I_DOWN_SPEED_SPIN           15033
#define IDC_TIME_DOWN                   15034
#define IDC_TIME_DOWN_SPIN              15035
#define IDC_H_DOWN_SPEED                15036
#define IDC_H_DOWN_SPEED_SPIN           15037
#define IDC_SETTINGS_KBPS5              15038
#define IDC_SETTINGS_KBPS6              15039
#define IDC_SETTINGS_MINUTES            15040
#define IDC_MIN_FILE_SIZE_SPIN          15041
#define IDC_SETTINGS_MB                 15042
#define IDC_CZDC_MIN_FILE_SIZE          15043
#define IDC_REMOVE_IF                   15044
#define IDC_REMOVE_IF_BELOW             15045
#define IDC_REMOVE_SPIN                 15046
#define IDC_SETTINGS_KBPS7              15047
#define IDC_CZDC_H_DOWN_SPEED           15048
#define IDC_SEGMENTED_ONLY              15049
#define IDC_SEARCH_FAKE_DLG_SEARCH_STRING 15050
#define IDC_AS_SEARCH_STRING            15051
#define IDC_MIN_SEGMENT_SIZE            15051
#define IDC_ADD_SRCH_STR_TYPE_STATIC    15052
#define IDC_AS_ACTION_STATIC            15053
#define IDC_AS_ACTION                   15054
#define IDC_AS_FILETYPE                 15055
#define IDC_AUTOSEARCH_ITEMS            15056
#define IDC_AUTOSEARCH_ENABLE_TIME      15058
#define IDC_AUTOSEARCH_EVERY            15059
#define IDC_AUTOSEARCH_SPIN             15060
#define IDC_AUTOSEARCH_ENABLE           15061
#define IDC_AUTOSEARCH_RECHECK_TIME     15062
#define IDC_AUTOSEARCH_RECHECK_SPIN     15063
#define IDC_MINUTES2                    15064
#define IDC_AUTOSEARCH_RECHECK_TEXT     15065
#define IDC_DUPES                       15066
#define IDC_DUPE_COLOR                  15067
#define IDC_DUPE_DESCRIPTION            15068
#define IDC_OPEN                        15069
#define IDC_EXCL_CHECKS                 15070
#define IDC_OPEN_DOWNLOADS_T            15074
#define IDC_REFRESH_FILE_LIST_T         15075
#define IDC_SWITCH_WINDOW_1             15077
#define IDC_SWITCH_WINDOW_2             15078
#define IDC_SWITCH_WINDOW_3             15079
#define IDC_SWITCH_WINDOW_4             15080
#define IDC_SWITCH_WINDOW_5             15081
#define IDC_SWITCH_WINDOW_6             15082
#define IDC_SWITCH_WINDOW_7             15083
#define IDC_SWITCH_WINDOW_8             15084
#define IDC_SWITCH_WINDOW_9             15085
#define IDC_SWITCH_WINDOW_0             15086
#define IDC_REGEXP_TEST                 15087
#define IDC_ADLS_COMMENT_STRING         15088
#define IDC_IS_CASE_SENSITIVE           15089
#define IDC_REGEXP_TESTER               15090
#define IDC_ADLS_COMMENT                15091
#define IDC_TEST_STRING                 15092
#define IDC_MIN_SEGMENT_SIZE_LABEL      15093
#define IDC_SETTINGS_SEGMENTS           15094
#define IDC_UPDATE_LANGUAGE_BUTTON      15096
#define IDC_LANGDOWNLOAD                15097
#define IDC_UPDATE_LANGUAGE_CURRENT_LBL 15098
#define IDC_UPDATE_LANGUAGE_LATEST_LBL  15099
#define IDC_UPDATE_LANGUAGELANG_CURRENT_LBL 15100
#define IDC_UPDATE_LANGUAGELANG_CURRENT 15101
#define IDC_ALLOW_CONNECTION_TO_PASSED_HUBS 15102
#define IDR_HUB_OP                      15103
#define IDR_HUB_REG                     15104
#define IDC_SCANLIST                    15105
#define IDC_VIEW_NFO                    15106
#define IDC_HELP_FAQ                    15107
#define IDC_DL_SEARCH_DESC              15108
#define IDC_DL_FILETYPE                 15109
#define IDC_DL_SEARCH_STRING            15110
#define IDC_DL_TYPE_TEXT                15111
#define IDC_REMOVE_BUNDLE               15112
#define IDC_OPEN_BUNDLE_FOLDER          15114
#define IDC_BUNDLE_PRIORITY             15115
#define IDC_REMOVE_BUNDLE_SOURCE        15116
#define IDC_RELOAD                      15117
#define ID_TOGGLE_TOOLBAR               15999
#define IDC_BITZI_LOOKUP                20000
#define IDC_BROWSELIST                  21000
#define IDC_REMOVE_SOURCE               23000
#define IDC_PM                          25000
#define IDC_READD                       27000
#define IDC_REMOVE_SOURCES              29000
#define ID_FILE_CONNECT                 32772
#define ID_FILE_SETTINGS                32774
#define ID_FILE_RECONNECT               32775
#define ID_FILE_SEARCH                  32776
#define ID_FILE_QUICK_CONNECT           32777
#define IDC_DOWNLOAD                    32780
#define IDC_DOWNLOADTO                  32781
#define IDC_RECENTS                     32782
#define IDC_FAVORITES                   32783
#define IDC_FOLLOW                      32784
#define IDC_SEND_MESSAGE                32786
#define IDC_FILTER_FOCUS                32788
#define ID_WINDOW_MINIMIZE_ALL          57654
#define ID_WINDOW_RESTORE_ALL           57655
#define IDC_WINAMP_START                57666
#define IDC_CHATCOLORS                  65535

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        320
#define _APS_NEXT_COMMAND_VALUE         32795
#define _APS_NEXT_CONTROL_VALUE         1619
#define _APS_NEXT_SYMED_VALUE           136
#endif
#endif
