image: Visual Studio 2022
configuration: Debug
platform: x64
install:
- cd C:\Tools\vcpkg
- git pull
- .\bootstrap-vcpkg.bat
- cd %APPVEYOR_BUILD_FOLDER%
before_build:
  - cmake "-DCMAKE_VS_GLOBALS=UseMultiToolTask=true;EnforceProcessCountAcrossBuilds=true" -B msvc -G "Visual Studio 17 2022" . --preset %PLATFORM%-debug
build:
  project: $(APPVEYOR_BUILD_FOLDER)\msvc\$(APPVEYOR_PROJECT_NAME).sln
  parallel: true
  verbosity: normal
cache:
- c:\tools\vcpkg\installed\
init:
  # Set "build version number" to "short-commit-hash" or when tagged to "tag name" (Travis style)
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true")
      {
        Update-AppveyorBuild -Version "$env:APPVEYOR_REPO_TAG_NAME"
      }
      else
      {
        Update-AppveyorBuild -Version "dev-$($env:APPVEYOR_REPO_COMMIT.substring(0,7))"
      }
